### ISSUE TITLE
【疑似BUG】当添加有较多子文件和子文件夹的项目时，添加失败

### ISSUE THREAD

**Issue by bennylii** [666wcy/pikpakdown#5]
## 问题描述
当添加有较多子文件和子文件夹的项目时，添加失败
测试：本地下载，失败
迅雷，没有
aria2，无法连接
IDM，失败

希望能实现类似于隔壁   https://github.com/liupan1890/aliyunpan    的操作，获取单个链接而不是一次性获取链接

## 报错日志
```
INFO (2021-12-17 02:09:00):登录过期，正在重新登录
Error (2021-12-17 02:10:02):本地aria2未启动,即将启动
INFO (2021-12-17 02:10:03):本地Aria2启动成功
INFO (2021-12-17 02:10:03):内部下载添加任务：PikPak Tutorial.mp4 路径:G:/cache/
INFO (2021-12-17 02:11:59):内部下载,识别为文件夹:[2000-2002] Azumanga Daioh_笑園漫畫大王(あずまんが大王)_ONA.MOVIE.TV
Error (2021-12-17 02:14:39):修改item线程错误:'NoneType' object has no attribute 'setToolTip'
Error (2021-12-17 02:14:39):修改item线程错误:'NoneType' object has no attribute 'setToolTip'
Error (2021-12-17 02:14:39):修改item线程错误:'NoneType' object has no attribute 'setToolTip'
Error (2021-12-17 02:14:39):修改item线程错误:'NoneType' object has no attribute 'setToolTip'
Error (2021-12-17 02:14:40):修改item线程错误:'NoneType' object has no attribute 'setToolTip'
Error (2021-12-17 02:14:41):修改item线程错误:'NoneType' object has no attribute 'setToolTip'
Error (2021-12-17 02:14:44):修改item线程错误:'NoneType' object has no attribute 'setToolTip'
Error (2021-12-17 02:14:47):修改item线程错误:'NoneType' object has no attribute 'setToolTip'
Error in sys.excepthook: Traceback (most recent call last): File "E:\cache_waiting_to_delete\win64\cgitb.py", line 270, in __call__ File "E:\cache_waiting_to_delete\win64\cgitb.py", line 290, in handle Attribute
Error: 'NoneType' object has no attribute 'write'Original exception was: Traceback (most recent call last): File "E:\cache_waiting_to_delete\win64\urllib3\connectionpool.py", line 381, in _make_request self._validate_conn(conn)File "E:\cache_waiting_to_delete\win64\urllib3\connectionpool.py", line 978, in _validate_conn conn.connect()File "E:\cache_waiting_to_delete\win64\urllib3\connection.py", line 362, in connect self.sock = ssl_wrap_socket(File "E:\cache_waiting_to_delete\win64\urllib3\util\ssl_.py", line 386, in ssl_wrap_socket return context.wrap_socket(sock, server_hostname=server_hostname)File "E:\cache_waiting_to_delete\win64\ssl.py", line 500, in wrap_socket File "E:\cache_waiting_to_delete\win64\ssl.py", line 1040, in _create File "E:\cache_waiting_to_delete\win64\ssl.py", line 1309, in do_handshake socket.timeout: _ssl.c:1114: The handshake operation timed outDuring handling of the above exception, another exception occurred: Traceback (most recent call last): File "E:\cache_waiting_to_delete\win64\requests\adapters.py", line 439, in send resp = conn.urlopen(File "E:\cache_waiting_to_delete\win64\urllib3\connectionpool.py", line 726, in urlopen retries = retries.increment(File "E:\cache_waiting_to_delete\win64\urllib3\util\retry.py", line 410, in increment raise six.reraise(type(error), error, _stacktrace)File "E:\cache_waiting_to_delete\win64\urllib3\packages\six.py", line 735, in reraise raise valueFile "E:\cache_waiting_to_delete\win64\urllib3\connectionpool.py", line 670, in urlopen httplib_response = self._make_request(File "E:\cache_waiting_to_delete\win64\urllib3\connectionpool.py", line 384, in _make_request self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)File "E:\cache_waiting_to_delete\win64\urllib3\connectionpool.py", line 335, in _raise_timeout raise ReadTimeout
Error(urllib3.exceptions.ReadTimeout
Error: HTTPSConnectionPool(host='api-drive.mypikpak.com', port=443): Read timed out. (read timeout=5)During handling of the above exception, another exception occurred: Traceback (most recent call last): File "E:\cache_waiting_to_delete\win64\pikpakdown.py", line 1248, in run File "E:\cache_waiting_to_delete\win64\need\pikabout.py", line 251, in get_download_url File "E:\cache_waiting_to_delete\win64\requests\api.py", line 76, in get return request('get', url, params=params, **kwargs)File "E:\cache_waiting_to_delete\win64\requests\api.py", line 61, in request return session.request(method=method, url=url, **kwargs)File "E:\cache_waiting_to_delete\win64\requests\sessions.py", line 530, in request resp = self.send(prep, **send_kwargs)File "E:\cache_waiting_to_delete\win64\requests\sessions.py", line 643, in send r = adapter.send(request, **kwargs)File "E:\cache_waiting_to_delete\win64\requests\adapters.py", line 529, in send raise ReadTimeout(e, request=request)requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api-drive.mypikpak.com', port=443): Read timed out. (read timeout=5)During handling of the above exception, another exception occurred: Traceback (most recent call last): File "E:\cache_waiting_to_delete\win64\pikpakdown.py", line 1278, in run File "E:\cache_waiting_to_delete\win64\cgitb.py", line 270, in __call__ File "E:\cache_waiting_to_delete\win64\cgitb.py", line 288, in handle Attribute
Error: 'NoneType' object has no attribute 'write'
Error in sys.excepthook: Traceback (most recent call last): File "E:\cache_waiting_to_delete\win64\cgitb.py", line 270, in __call__ File "E:\cache_waiting_to_delete\win64\cgitb.py", line 290, in handle Attribute
Error: 'NoneType' object has no attribute 'write'Original exception was: Traceback (most recent call last): File "E:\cache_waiting_to_delete\win64\urllib3\connectionpool.py", line 381, in _make_request self._validate_conn(conn)File "E:\cache_waiting_to_delete\win64\urllib3\connectionpool.py", line 978, in _validate_conn conn.connect()File "E:\cache_waiting_to_delete\win64\urllib3\connection.py", line 362, in connect self.sock = ssl_wrap_socket(File "E:\cache_waiting_to_delete\win64\urllib3\util\ssl_.py", line 386, in ssl_wrap_socket return context.wrap_socket(sock, server_hostname=server_hostname)File "E:\cache_waiting_to_delete\win64\ssl.py", line 500, in wrap_socket File "E:\cache_waiting_to_delete\win64\ssl.py", line 1040, in _create File "E:\cache_waiting_to_delete\win64\ssl.py", line 1309, in do_handshake socket.timeout: _ssl.c:1114: The handshake operation timed outDuring handling of the above exception, another exception occurred: Traceback (most recent call last): File "E:\cache_waiting_to_delete\win64\requests\adapters.py", line 439, in send resp = conn.urlopen(File "E:\cache_waiting_to_delete\win64\urllib3\connectionpool.py", line 726, in urlopen retries = retries.increment(File "E:\cache_waiting_to_delete\win64\urllib3\util\retry.py", line 410, in increment raise six.reraise(type(error), error, _stacktrace)File "E:\cache_waiting_to_delete\win64\urllib3\packages\six.py", line 735, in reraise raise valueFile "E:\cache_waiting_to_delete\win64\urllib3\connectionpool.py", line 670, in urlopen httplib_response = self._make_request(File "E:\cache_waiting_to_delete\win64\urllib3\connectionpool.py", line 384, in _make_request self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)File "E:\cache_waiting_to_delete\win64\urllib3\connectionpool.py", line 335, in _raise_timeout raise ReadTimeout
Error(urllib3.exceptions.ReadTimeout
Error: HTTPSConnectionPool(host='api-drive.mypikpak.com', port=443): Read timed out. (read timeout=5)During handling of the above exception, another exception occurred: Traceback (most recent call last): File "E:\cache_waiting_to_delete\win64\pikpakdown.py", line 1258, in run File "E:\cache_waiting_to_delete\win64\need\pikabout.py", line 449, in get_folder_all_file File "E:\cache_waiting_to_delete\win64\need\pikabout.py", line 449, in get_folder_all_file File "E:\cache_waiting_to_delete\win64\need\pikabout.py", line 442, in get_folder_all_file File "E:\cache_waiting_to_delete\win64\need\pikabout.py", line 251, in get_download_url File "E:\cache_waiting_to_delete\win64\requests\api.py", line 76, in get return request('get', url, params=params, **kwargs)File "E:\cache_waiting_to_delete\win64\requests\api.py", line 61, in request return session.request(method=method, url=url, **kwargs)File "E:\cache_waiting_to_delete\win64\requests\sessions.py", line 530, in request resp = self.send(prep, **send_kwargs)File "E:\cache_waiting_to_delete\win64\requests\sessions.py", line 643, in send r = adapter.send(request, **kwargs)File "E:\cache_waiting_to_delete\win64\requests\adapters.py", line 529, in send raise ReadTimeout(e, request=request)requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api-drive.mypikpak.com', port=443): Read timed out. (read timeout=5)During handling of the above exception, another exception occurred: Traceback (most recent call last): File "E:\cache_waiting_to_delete\win64\pikpakdown.py", line 1278, in run File "E:\cache_waiting_to_delete\win64\cgitb.py", line 270, in __call__ File "E:\cache_waiting_to_delete\win64\cgitb.py", line 288, in handle Attribute
Error: 'NoneType' object has no attribute 'write'
Error (2021-12-17 02:16:08):修改item线程错误:'NoneType' object has no attribute 'setToolTip'
```

## 测试用例
秒传导出失败
`magnet:?xt=urn:btih:b3b4ec3858b6e03d376b4fcc44effeea19c2609a&tr=http://open.acgtracker.com:1096/announce`

**Comment by bennylii** [comment]
再补一段：
```
INFO (2021-12-17 02:39:19):内部下载,识别为文件夹:[2000-2002] Azumanga Daioh_笑園漫畫大王(あずまんが大王)_ONA.MOVIE.TV
Error in sys.excepthook: Traceback (most recent call last): File "E:\cache_waiting_to_delete\win64\cgitb.py", line 270, in __call__ File "E:\cache_waiting_to_delete\win64\cgitb.py", line 290, in handle Attribute
Error: 'NoneType' object has no attribute 'write'Original exception was: Traceback (most recent call last): File "E:\cache_waiting_to_delete\win64\urllib3\connectionpool.py", line 381, in _make_request self._validate_conn(conn)File "E:\cache_waiting_to_delete\win64\urllib3\connectionpool.py", line 978, in _validate_conn conn.connect()File "E:\cache_waiting_to_delete\win64\urllib3\connection.py", line 362, in connect self.sock = ssl_wrap_socket(File "E:\cache_waiting_to_delete\win64\urllib3\util\ssl_.py", line 386, in ssl_wrap_socket return context.wrap_socket(sock, server_hostname=server_hostname)File "E:\cache_waiting_to_delete\win64\ssl.py", line 500, in wrap_socket File "E:\cache_waiting_to_delete\win64\ssl.py", line 1040, in _create File "E:\cache_waiting_to_delete\win64\ssl.py", line 1309, in do_handshake socket.timeout: _ssl.c:1114: The handshake operation timed outDuring handling of the above exception, another exception occurred: Traceback (most recent call last): File "E:\cache_waiting_to_delete\win64\requests\adapters.py", line 439, in send resp = conn.urlopen(File "E:\cache_waiting_to_delete\win64\urllib3\connectionpool.py", line 726, in urlopen retries = retries.increment(File "E:\cache_waiting_to_delete\win64\urllib3\util\retry.py", line 410, in increment raise six.reraise(type(error), error, _stacktrace)File "E:\cache_waiting_to_delete\win64\urllib3\packages\six.py", line 735, in reraise raise valueFile "E:\cache_waiting_to_delete\win64\urllib3\connectionpool.py", line 670, in urlopen httplib_response = self._make_request(File "E:\cache_waiting_to_delete\win64\urllib3\connectionpool.py", line 384, in _make_request self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)File "E:\cache_waiting_to_delete\win64\urllib3\connectionpool.py", line 335, in _raise_timeout raise ReadTimeout
Error(urllib3.exceptions.ReadTimeout
Error: HTTPSConnectionPool(host='api-drive.mypikpak.com', port=443): Read timed out. (read timeout=5)During handling of the above exception, another exception occurred: Traceback (most recent call last): File "E:\cache_waiting_to_delete\win64\pikpakdown.py", line 1258, in run File "E:\cache_waiting_to_delete\win64\need\pikabout.py", line 449, in get_folder_all_file File "E:\cache_waiting_to_delete\win64\need\pikabout.py", line 449, in get_folder_all_file File "E:\cache_waiting_to_delete\win64\need\pikabout.py", line 442, in get_folder_all_file File "E:\cache_waiting_to_delete\win64\need\pikabout.py", line 251, in get_download_url File "E:\cache_waiting_to_delete\win64\requests\api.py", line 76, in get return request('get', url, params=params, **kwargs)File "E:\cache_waiting_to_delete\win64\requests\api.py", line 61, in request return session.request(method=method, url=url, **kwargs)File "E:\cache_waiting_to_delete\win64\requests\sessions.py", line 530, in request resp = self.send(prep, **send_kwargs)File "E:\cache_waiting_to_delete\win64\requests\sessions.py", line 643, in send r = adapter.send(request, **kwargs)File "E:\cache_waiting_to_delete\win64\requests\adapters.py", line 529, in send raise ReadTimeout(e, request=request)requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api-drive.mypikpak.com', port=443): Read timed out. (read timeout=5)During handling of the above exception, another exception occurred: Traceback (most recent call last): File "E:\cache_waiting_to_delete\win64\pikpakdown.py", line 1278, in run File "E:\cache_waiting_to_delete\win64\cgitb.py", line 270, in __call__ File "E:\cache_waiting_to_delete\win64\cgitb.py", line 288, in handle Attribute
Error: 'NoneType' object has no attribute 'write'
```

**Comment by 666wcy** [comment]
新版本已修复，测试超300文件无异常
